default_platform(:android)

platform :android do
  desc "Lane for android firebase app distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:917265294655:android:8415d30653a43a046bdf8a",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      testers: "mostafaramadanhamed010@gmail.com",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      release_notes: "first fastlane firebase app distribution",
    )

  end
end
